name: build-test-benchmark 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: mkdir build && cmake -B build -S . -DCMAKE_BUILD_TYPE=Release && cmake --build build
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            build/bin/summator
            build/bin/tests
            build/bin/g_benchmark

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x tests && ./tests

  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x summator && ./summator 2 7

  benchmark:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x g_benchmark && ./g_benchmark
